{"kind":"symbol","metadata":{"roleHeading":"Instance Property","extendedModule":"CloudXCore","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"symbolKind":"property","modules":[{"name":"CloudXCore"}],"role":"symbol","title":"errorDescription","externalID":"s:10CloudXCore0A6XErrorO16errorDescriptionSSSgvp"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/cloudxcore\/cloudxerror\/errordescription"]}],"sections":[],"abstract":[{"text":"A localized message describing what error occurred.","type":"text"}],"identifier":{"url":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/errorDescription","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/LocalizedError-Implementations"]]},"references":{"doc://com.cloudx.sdk.core/documentation/CloudXCore":{"identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","abstract":[],"title":"CloudXCore","type":"topic","url":"\/documentation\/cloudxcore","kind":"symbol","role":"collection"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError":{"identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CloudXError","kind":"identifier"}],"type":"topic","abstract":[{"text":"An error type that represents the CloudX SDK errors.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"CloudXError","kind":"identifier"}],"title":"CloudXError","url":"\/documentation\/cloudxcore\/cloudxerror"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/errorDescription":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","title":"errorDescription","url":"\/documentation\/cloudxcore\/cloudxerror\/errordescription","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/errorDescription","abstract":[{"type":"text","text":"A localized message describing what error occurred."}]},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/LocalizedError-Implementations":{"identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/LocalizedError-Implementations","abstract":[],"title":"LocalizedError Implementations","type":"topic","kind":"article","role":"collectionGroup","url":"\/documentation\/cloudxcore\/cloudxerror\/localizederror-implementations"}}}