{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"A localized message describing what error occurred.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"CloudXCore"}],"extendedModule":"CloudXCore","externalID":"s:10CloudXCore0A6XErrorO16errorDescriptionSSSgvp","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"errorDescription","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/LocalizedError-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/errorDescription"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/cloudxcore\/cloudxerror\/errordescription"]}],"references":{"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError":{"type":"topic","title":"CloudXError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CloudXError"}],"navigatorTitle":[{"kind":"identifier","text":"CloudXError"}],"url":"\/documentation\/cloudxcore\/cloudxerror","abstract":[{"type":"text","text":"An error type that represents the CloudX SDK errors."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/errorDescription":{"role":"symbol","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/cloudxcore\/cloudxerror\/errordescription","kind":"symbol","abstract":[{"type":"text","text":"A localized message describing what error occurred."}],"title":"errorDescription"},"doc://com.cloudx.sdk.core/documentation/CloudXCore":{"abstract":[],"type":"topic","url":"\/documentation\/cloudxcore","title":"CloudXCore","kind":"symbol","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","role":"collection"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/LocalizedError-Implementations":{"url":"\/documentation\/cloudxcore\/cloudxerror\/localizederror-implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/LocalizedError-Implementations","kind":"article","title":"LocalizedError Implementations","type":"topic"}}}