{"abstract":[{"text":"A localized message describing what error occurred.","type":"text"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/errorDescription"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/cloudxcore\/cloudxerror\/errordescription"]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"extendedModule":"CloudXCore","modules":[{"name":"CloudXCore"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"s:10CloudXCore0A6XErrorO16errorDescriptionSSSgvp","title":"errorDescription","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/LocalizedError-Implementations"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/errorDescription":{"abstract":[{"type":"text","text":"A localized message describing what error occurred."}],"title":"errorDescription","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/errorDescription","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/cloudxcore\/cloudxerror\/errordescription","type":"topic","role":"symbol"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/LocalizedError-Implementations":{"kind":"article","type":"topic","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/LocalizedError-Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/cloudxcore\/cloudxerror\/localizederror-implementations","title":"LocalizedError Implementations"},"doc://com.cloudx.sdk.core/documentation/CloudXCore":{"url":"\/documentation\/cloudxcore","type":"topic","role":"collection","title":"CloudXCore","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CloudXError","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"CloudXError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError","abstract":[{"text":"An error type that represents the CloudX SDK errors.","type":"text"}],"role":"symbol","url":"\/documentation\/cloudxcore\/cloudxerror","title":"CloudXError"}}}