{"identifier":{"url":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/generalAdError","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"General ad error.","type":"text"}],"variants":[{"paths":["\/documentation\/cloudxcore\/cloudxerror\/generaladerror"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"generalAdError","kind":"identifier"}]}]}],"metadata":{"modules":[{"name":"CloudXCore"}],"externalID":"s:10CloudXCore0A6XErrorO14generalAdErroryA2CmF","title":"CloudXError.generalAdError","symbolKind":"case","role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"generalAdError","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError"]]},"references":{"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError":{"identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CloudXError","kind":"identifier"}],"type":"topic","abstract":[{"text":"An error type that represents the CloudX SDK errors.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"CloudXError","kind":"identifier"}],"title":"CloudXError","url":"\/documentation\/cloudxcore\/cloudxerror"},"doc://com.cloudx.sdk.core/documentation/CloudXCore":{"identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","abstract":[],"title":"CloudXCore","type":"topic","url":"\/documentation\/cloudxcore","kind":"symbol","role":"collection"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/generalAdError":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/generalAdError","url":"\/documentation\/cloudxcore\/cloudxerror\/generaladerror","title":"CloudXError.generalAdError","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generalAdError"}],"abstract":[{"text":"General ad error.","type":"text"}]}}}