{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/cloudxcore\/cloudxerror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError"]]},"metadata":{"modules":[{"name":"CloudXCore"}],"title":"LocalizedError Implementations","roleHeading":"API Collection","role":"collectionGroup"},"kind":"article","topicSections":[{"identifiers":["doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/errorDescription","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/failureReason","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/helpAnchor","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/recoverySuggestion"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"references":{"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/errorDescription":{"role":"symbol","title":"errorDescription","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/errorDescription","abstract":[{"type":"text","text":"A localized message describing what error occurred."}],"url":"\/documentation\/cloudxcore\/cloudxerror\/errordescription","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/failureReason":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/failureReason","abstract":[],"title":"failureReason","type":"topic","url":"\/documentation\/cloudxcore\/cloudxerror\/failurereason","kind":"symbol","role":"symbol"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/recoverySuggestion":{"identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/recoverySuggestion","type":"topic","role":"symbol","url":"\/documentation\/cloudxcore\/cloudxerror\/recoverysuggestion","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recoverySuggestion"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"recoverySuggestion","kind":"symbol"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/helpAnchor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/helpAnchor","abstract":[],"title":"helpAnchor","type":"topic","url":"\/documentation\/cloudxcore\/cloudxerror\/helpanchor","kind":"symbol","role":"symbol"},"doc://com.cloudx.sdk.core/documentation/CloudXCore":{"type":"topic","abstract":[],"title":"CloudXCore","role":"collection","kind":"symbol","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","url":"\/documentation\/cloudxcore"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError":{"url":"\/documentation\/cloudxcore\/cloudxerror","role":"symbol","kind":"symbol","title":"CloudXError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CloudXError","kind":"identifier"}],"type":"topic","abstract":[{"text":"An error type that represents the CloudX SDK errors.","type":"text"}],"navigatorTitle":[{"text":"CloudXError","kind":"identifier"}],"identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError"}}}