{"sections":[],"kind":"article","metadata":{"roleHeading":"API Collection","title":"LocalizedError Implementations","modules":[{"name":"CloudXCore"}],"role":"collectionGroup"},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/errorDescription","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/failureReason","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/helpAnchor","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/recoverySuggestion"]}],"variants":[{"paths":["\/documentation\/cloudxcore\/cloudxerror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError"]]},"references":{"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/recoverySuggestion":{"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recoverySuggestion"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/cloudxcore\/cloudxerror\/recoverysuggestion","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/recoverySuggestion","title":"recoverySuggestion","role":"symbol","abstract":[]},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/helpAnchor":{"title":"helpAnchor","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/helpAnchor","url":"\/documentation\/cloudxcore\/cloudxerror\/helpanchor"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/errorDescription":{"role":"symbol","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/errorDescription","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/cloudxcore\/cloudxerror\/errordescription","title":"errorDescription","abstract":[{"type":"text","text":"A localized message describing what error occurred."}],"kind":"symbol","type":"topic"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/failureReason":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"failureReason","kind":"symbol","type":"topic","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/failureReason","abstract":[],"url":"\/documentation\/cloudxcore\/cloudxerror\/failurereason"},"doc://com.cloudx.sdk.core/documentation/CloudXCore":{"role":"collection","kind":"symbol","title":"CloudXCore","type":"topic","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","abstract":[],"url":"\/documentation\/cloudxcore"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError":{"title":"CloudXError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CloudXError","kind":"identifier"}],"identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError","url":"\/documentation\/cloudxcore\/cloudxerror","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"CloudXError","kind":"identifier"}],"abstract":[{"type":"text","text":"An error type that represents the CloudX SDK errors."}]}}}