{"kind":"article","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/cloudxcore\/cloudxerror\/localizederror-implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/LocalizedError-Implementations"},"hierarchy":{"paths":[["doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError"]]},"metadata":{"role":"collectionGroup","modules":[{"name":"CloudXCore"}],"roleHeading":"API Collection","title":"LocalizedError Implementations"},"sections":[],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/errorDescription","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/failureReason","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/helpAnchor","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/recoverySuggestion"]}],"references":{"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/recoverySuggestion":{"title":"recoverySuggestion","kind":"symbol","url":"\/documentation\/cloudxcore\/cloudxerror\/recoverysuggestion","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/recoverySuggestion","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[],"type":"topic"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/helpAnchor":{"url":"\/documentation\/cloudxcore\/cloudxerror\/helpanchor","role":"symbol","title":"helpAnchor","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/helpAnchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","abstract":[]},"doc://com.cloudx.sdk.core/documentation/CloudXCore":{"url":"\/documentation\/cloudxcore","type":"topic","role":"collection","title":"CloudXCore","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CloudXError","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"CloudXError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError","abstract":[{"text":"An error type that represents the CloudX SDK errors.","type":"text"}],"role":"symbol","url":"\/documentation\/cloudxcore\/cloudxerror","title":"CloudXError"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/errorDescription":{"abstract":[{"type":"text","text":"A localized message describing what error occurred."}],"title":"errorDescription","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/errorDescription","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/cloudxcore\/cloudxerror\/errordescription","type":"topic","role":"symbol"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/failureReason":{"title":"failureReason","kind":"symbol","url":"\/documentation\/cloudxcore\/cloudxerror\/failurereason","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/failureReason","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[],"type":"topic"}}}