{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"CloudXCore"}],"title":"CloudXError.sdkInitialisationInProgress","externalID":"s:10CloudXCore0A6XErrorO27sdkInitialisationInProgressyA2CmF","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkInitialisationInProgress"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"sdkInitialisationInProgress","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/sdkInitialisationInProgress","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/cloudxcore\/cloudxerror\/sdkinitialisationinprogress"]}],"sections":[],"abstract":[{"type":"text","text":"If SDK initialisation is in progress and you try to initialise it again, this error will be thrown."}],"references":{"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/sdkInitialisationInProgress":{"role":"symbol","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/sdkInitialisationInProgress","abstract":[{"type":"text","text":"If SDK initialisation is in progress and you try to initialise it again, this error will be thrown."}],"title":"CloudXError.sdkInitialisationInProgress","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkInitialisationInProgress"}],"type":"topic","url":"\/documentation\/cloudxcore\/cloudxerror\/sdkinitialisationinprogress"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CloudXError","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"CloudXError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError","abstract":[{"text":"An error type that represents the CloudX SDK errors.","type":"text"}],"role":"symbol","url":"\/documentation\/cloudxcore\/cloudxerror","title":"CloudXError"},"doc://com.cloudx.sdk.core/documentation/CloudXCore":{"url":"\/documentation\/cloudxcore","type":"topic","role":"collection","title":"CloudXCore","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore"}}}