{"identifier":{"url":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/sdkInitialisationInProgress","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkInitialisationInProgress"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/cloudxcore\/cloudxerror\/sdkinitialisationinprogress"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Case","externalID":"s:10CloudXCore0A6XErrorO27sdkInitialisationInProgressyA2CmF","symbolKind":"case","title":"CloudXError.sdkInitialisationInProgress","modules":[{"name":"CloudXCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkInitialisationInProgress"}]},"sections":[],"kind":"symbol","abstract":[{"text":"If SDK initialisation is in progress and you try to initialise it again, this error will be thrown.","type":"text"}],"references":{"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError":{"title":"CloudXError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CloudXError","kind":"identifier"}],"identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError","url":"\/documentation\/cloudxcore\/cloudxerror","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"CloudXError","kind":"identifier"}],"abstract":[{"type":"text","text":"An error type that represents the CloudX SDK errors."}]},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/sdkInitialisationInProgress":{"role":"symbol","kind":"symbol","title":"CloudXError.sdkInitialisationInProgress","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/sdkInitialisationInProgress","type":"topic","url":"\/documentation\/cloudxcore\/cloudxerror\/sdkinitialisationinprogress","abstract":[{"type":"text","text":"If SDK initialisation is in progress and you try to initialise it again, this error will be thrown."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkInitialisationInProgress","kind":"identifier"}]},"doc://com.cloudx.sdk.core/documentation/CloudXCore":{"role":"collection","kind":"symbol","title":"CloudXCore","type":"topic","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","abstract":[],"url":"\/documentation\/cloudxcore"}}}