{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/sdkInitialisationInProgress","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/cloudxcore\/cloudxerror\/sdkinitialisationinprogress"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError"]]},"metadata":{"externalID":"s:10CloudXCore0A6XErrorO27sdkInitialisationInProgressyA2CmF","title":"CloudXError.sdkInitialisationInProgress","modules":[{"name":"CloudXCore"}],"roleHeading":"Case","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkInitialisationInProgress"}]},"abstract":[{"text":"If SDK initialisation is in progress and you try to initialise it again, this error will be thrown.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkInitialisationInProgress"}]}]}],"references":{"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError":{"url":"\/documentation\/cloudxcore\/cloudxerror","role":"symbol","kind":"symbol","title":"CloudXError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CloudXError","kind":"identifier"}],"type":"topic","abstract":[{"text":"An error type that represents the CloudX SDK errors.","type":"text"}],"navigatorTitle":[{"text":"CloudXError","kind":"identifier"}],"identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/sdkInitialisationInProgress":{"identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/sdkInitialisationInProgress","type":"topic","abstract":[{"type":"text","text":"If SDK initialisation is in progress and you try to initialise it again, this error will be thrown."}],"title":"CloudXError.sdkInitialisationInProgress","url":"\/documentation\/cloudxcore\/cloudxerror\/sdkinitialisationinprogress","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkInitialisationInProgress"}],"kind":"symbol"},"doc://com.cloudx.sdk.core/documentation/CloudXCore":{"type":"topic","abstract":[],"title":"CloudXCore","role":"collection","kind":"symbol","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","url":"\/documentation\/cloudxcore"}}}